spring:
  application:
    name: task-queue-service

  profiles:
    active: dev

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

server:
  port: 8080

app:
  storage:
    base-path: /data/uploads