spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/taskqueue}
    driver-class-name: org.postgresql.Driver
    username: ${DATABASE_USERNAME:admin}
    password: ${DATABASE_PASSWORD:admin}

  jpa:
    show-sql: false

logging:
  level:
    root: INFO
    com.example.taskqueue: DEBUG